### ISSUE TITLE
Error running  wsb config -ba under win10 x64

### ISSUE THREAD

**Issue by linuxlurak** [danny0838/PyWebScrapBook#25]
Executing wsb config -ba in powershell gives me this:
```
Traceback (most recent call last):
  File "c:\users\USER\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\USER\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36-32\Scripts\wsb.exe\__main__.py", line 9, in <module>
  File "c:\users\USER\appdata\local\programs\python\python36-32\lib\site-packages\webscrapbook\cli.py", line 615, in main
    help="""the conversion mode. Get usage help with e.g. %(prog)s sb2wsb -h""")
  File "c:\users\USER\appdata\local\programs\python\python36-32\lib\argparse.py", line 1703, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```
python --version
`Python 3.6.5
`

Can someone help? Are there modules missing?

**Comment by danny0838** [comment]
What is the version of your PyWebScrapBook? Run `wsb --version` to see it.

**Comment by linuxlurak** [comment]
It's webscrapbook 0.27.0

**Comment by danny0838** [comment]
Found the cause. A parameter not supported by Python 3.6.* was added in. Upgrading to 0.27.1 should fix it.

**Comment by linuxlurak** [comment]
superb. works now. thanks! (@danny0838 unbeatable response time!)
