### ISSUE TITLE
Confusing message from test.test_scrapbook_convert_wsb2sb.TestRun.test_meta_type01

### ISSUE THREAD

**Issue by maxnikulin** [danny0838/PyWebScrapBook#39]
I have noticed that the following test spits a stack trace
```
python3 -m unittest test.test_scrapbook_convert_wsb2sb.TestRun.test_meta_type01
Traceback (most recent call last):
  File "/home/ubuntu/danny0838/PyWebScrapBook/webscrapbook/scrapbook/convert/wsb2sb.py", line 357, in run
    yield from conv.run()
  File "/home/ubuntu/danny0838/PyWebScrapBook/webscrapbook/scrapbook/convert/wsb2sb.py", line 61, in run
    yield from self._copy_data_files(book)
  File "/home/ubuntu/danny0838/PyWebScrapBook/webscrapbook/scrapbook/convert/wsb2sb.py", line 266, in _copy_data_files
    content = book.load_note_file(file)
  File "/home/ubuntu/danny0838/PyWebScrapBook/webscrapbook/scrapbook/book.py", line 412, in load_note_file
    with open(file, encoding='UTF-8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/danny0838/PyWebScrapBook/test/test_scrapbook_convert/output/data/20200101000000/index.html'
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
```

I guess, absent file and the error is expected behavior. Unfortunately during run of all tests it is not obvious which test causes this message and if that is a sign of real error that is ignored for some reason.

Is it possible to suppress this message? Anyway other messages from converter are ignored. At least a message could be added to clarify that is expected failure. Another option is to create the expected file in the test, would you mind against such fix?

**Comment by danny0838** [comment]
Well, we do have missed to check for the index.html file. Fixed it. Thank you for the report.
